packages:
  - packages/*
  - playground

catalog:
  tsdown: ^0.22.2
  '@vueuse/core': ^13.0.0
  vue: ^3.5.32
  '@iconify-json/carbon': ^1.2.8
  '@unocss/preset-icons': ^66.1.0
  '@unocss/reset': ^66.1.0
  '@unocss/transformer-variant-group': ^66.1.0
  '@vitejs/plugin-vue': ^6.0.6
  unocss: ^66.1.0
  unplugin-vue-components: ^28.4.1
  vite: ^8.0.8
  vite-plugin-pwa: ^1.0.0

onlyBuiltDependencies:
  - esbuild
