// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AsmResult: typeof import('./src/components/AsmResult.vue')['default']
    DisasmResult: typeof import('./src/components/DisasmResult.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    Switch: typeof import('./src/components/ui/Switch.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
