/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DisasmResult: typeof import('./src/components/DisasmResult.vue')['default']
    HexResult: typeof import('./src/components/HexResult.vue')['default']
    PanelToolbar: typeof import('./src/components/ui/PanelToolbar.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    Switch: typeof import('./src/components/ui/Switch.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
